version: '2.1'
services: 
  web-proxy:
    image: miton18/web-proxy
    # will EXPOSE 80 443 8080
    ports: 
      - 80:80
      - 443:443
      - 8080:8080
    #network_mode: "host"
    environment:
      NODE_ENV: "production" 
      PROXY_MONGODB_ADDON_URI: "mongodb://web-proxy-mongo:27017/proxy"
      PROXY_JWT_SECRET: "myJWTSecret"
      PROXY_PEPPER: "myPasswordPepper"
      PROXY_JWT_ISSUER: "myJWTIssuer"
      PROXY_JWT_AUDIENCE: "myJWTAudience"
    depends_on:
      - "web-proxy-mongo"

  web-proxy-mongo:
    image: mongo
    ports: 
      - 27017:27017
#    volumes: 
#      - mongo-data:/data/db
#volumes: 
#  mongo-data:
